import { ModuleStoreApp } from "@projectbooth/module-store-ui";
import { StorageApp } from "@projectbooth/storage-ui";
import { CatalogApp } from "@projectbooth/catalog-ui";
import { PipelineApp } from "@projectbooth/pipeline-ui";
// pipeline-ui's dist/style.css is the one module stylesheet still imported here (ADR
// 0097): besides Tailwind utilities -- now regenerated by this shell's own build
// instead, since tailwind.config.ts's content glob scans every module's dist/**/*.js
// directly -- it also carries @xyflow/react's own hand-authored base CSS
// (`.react-flow__*`, the `dashdraw` keyframe for animated DAG edges) that no amount of
// content-scanning can regenerate, since it was never a Tailwind utility class to begin
// with. Dropping this import entirely would silently break the DAG canvas's rendering.
// See README.md's "Native module UI package obligations".
import "@projectbooth/pipeline-ui/dist/style.css";
import { LoggingApp } from "@projectbooth/logging-ui";
import { DatabaseApp } from "@projectbooth/database-ui";
import { LakehouseApp } from "@projectbooth/lakehouse-ui";
import { MODULE_STORE_SLOT_ID, registerNativeModule } from "@/lib/nativeModules";

/**
 * Every native-mode module's npm package gets registered here, per ADR 0030
 * (../booth-architecture/decisions/0030-native-module-ui-delivered-as-npm-package.md).
 * Imported once, for its side effects, from src/main.tsx before the app renders. The key
 * is the module's manifest `id`, which is what NativeModulePane looks up — a module with
 * no entry here shows the "aren't wired into the shell yet" placeholder, so adding a
 * native module's package to package.json without registering it here does nothing.
 *
 * Each package's ModuleProps are a superset of NativeModuleProps (ADR 0031/0033:
 * workspace, role, theme, getAccessToken); their remaining props are optional, so a bare
 * registration type-checks and works.
 */

// Module Store is shell-level (ADR 0027), not an entry in the module list, so it has its
// own reserved slot id rather than a manifest id.
registerNativeModule(MODULE_STORE_SLOT_ID, ModuleStoreApp);

// The combined StorageApp, not StorageBrowseApp/StorageAdminApp separately: the shell
// mounts one component per module id for both the module's navPath and adminNavPath, and
// StorageApp reads the current path itself to choose between its browse and admin views.
registerNativeModule("storage", StorageApp);

// A single view (its own routes live beneath the module's navPath); no admin split.
registerNativeModule("catalog", CatalogApp);

// A single view; ships its own DAG-rendering dependency (@xyflow/react) bundled in,
// rather than as a peer, since the shell doesn't provide one.
registerNativeModule("pipeline", PipelineApp);

// A single view: browse/filter/search every module's stdout/stderr logs (ADR 0015,
// ADR 0022's node-level collector). booth-logging's own power-user view (Grafana,
// ADR 0076) is iframe-proxy, not this — this is only the native browse/filter viewer.
registerNativeModule("logging", LoggingApp);

// A single, read-only status view (ADR 0093): the workspace's own database, plus every
// workspace's for an operator. No create/change/drop path exists here at all
// (ADR 0089) — status only. No adminNavPath split, unlike storage.
registerNativeModule("database", DatabaseApp);

// A single, read-only list of warehouses and their cheap status (ADR 0093). No
// create/delete action here — creating stays in the client library, deleting is
// undecided. No adminNavPath split, same shape as database.
registerNativeModule("lakehouse", LakehouseApp);
